ip_nexthop,cmdgen: add group extension and code refactor for cmdgen
okda-networks/iproute2-sysrepo pull request #25
Opened 2024-02-26 23:49 UTC by Ali-aqrabawi

[+] added group extension to ip-nexthop and group separator 
[+] changed cmdgen logic to generate args for starcmd, this will allow us to change the lyd_node before passing to the args generator usefull for iproute replace action.

2024-02-27 09:58 UTC, adaraiseh requested changes

2024-02-27 09:58 UTC, adaraiseh commented on src/lib/change_cmdgen.c
> +                    token = strtok(on_update_include, ",");
can we make this a function ?

2024-02-27 09:58 UTC, adaraiseh commented on src/lib/change_cmdgen.c
> +                    token = strtok(on_update_include, ",");
pull from sysrepo:
input: node name(s)
output: either lyd_node or cmd args list

2024-02-27 22:42 UTC, vjardin approved these changes
some cosmetics, this same commit does many things:
  - adding/changing some features
  - updating some cosmetics
  - fixing some logics
at least, it should deserve 3 separate commits with their respective commit logs.

2024-02-27 22:42 UTC, merged

2024-02-28 06:49 UTC, Ali-aqrabawi commented
It the same. Adding support for grouping through ip_nexthop. I can't add the support if the yang yang where grouing is used is not there (ip_nexthop). The code logic is needed for the same support. But added it as details.