iproute2: lib/json_print.c patch to send its outputs to memory buffer
okda-networks/iproute2-sysrepo pull request #34
Opened 2024-03-02 01:13 UTC by adaraiseh

Starting point to go with this implementation plan:
1. oper_data_cmdgen --> translates operational data sysrepo requests to iproute2 show commands
2. Outputs of show commands are stored in a memory buffer (json_buffer) instead of sending them to stdout (this PR).
3. Access the data once do_cmd is done and change json to lyd to be sent to sysrepo

2024-03-02 11:23 UTC, Ali-aqrabawi commented on src/iproute2_sysrepo.c
> +    } else {
please remove the test,

2024-03-02 11:40 UTC, Ali-aqrabawi requested changes
fantastic! tested it locally.

let's have the oper data support added with single.

2024-03-02 13:22 UTC, vjardin approved these changes
It is a nice step forward.

Let's chat for an alternative to avoid patching ; I need first to PoC few trials.

2024-03-04 08:21 UTC, Ali-aqrabawi approved these changes

2024-03-04 19:13 UTC, merged